services:
    Enetpartner\Vslinkcomposer\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Enetpartner\Vslinkcomposer\Service\:
        resource: '../src/Service'
        tags: ['controller.service_arguments']

    Enetpartner\Vslinkcomposer\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments'] 

